export const styles = {
  inp: {
    width: "100%",
    border: "1.5px solid #d0d8f0",
    borderRadius: 7,
    padding: "9px 12px",
    fontSize: 13,
    outline: "none",
    color: "#333",
    background: "#fff",
    fontFamily: "inherit",
  },
  sel: {
    width: "100%",
    border: "1.5px solid #d0d8f0",
    borderRadius: 7,
    padding: "9px 12px",
    fontSize: 13,
    outline: "none",
    color: "#333",
    background: "#fff",
    fontFamily: "inherit",
  },
  ta: {
    width: "100%",
    border: "1.5px solid #d0d8f0",
    borderRadius: 7,
    padding: "9px 12px",
    fontSize: 13,
    outline: "none",
    color: "#333",
    background: "#fff",
    fontFamily: "inherit",
    resize: "vertical",
    minHeight: 90,
    lineHeight: 1.6,
  },
};